// Code generated by protoc-gen-go. DO NOT EDIT.
// source: btdxcx.com/micro/member-srv/proto/member/member.proto

/*
Package com_btdxcx_micro_srv_member is a generated protocol buffer package.

It is generated from these files:
	btdxcx.com/micro/member-srv/proto/member/member.proto

It has these top-level messages:
	CreateCustomerRequest
	CustomerResponse
	ReadCustomersRequest
	ReadCustomersResponse
	ReadCustomerRequest
	UpdateCustomerRequest
	DeleteCustomerRequest
	DeleteCustomerResponse
	CustomerRecord
*/
package com_btdxcx_micro_srv_member

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateCustomerRequest struct {
	ShopId string          `protobuf:"bytes,1,opt,name=shop_id,json=shopId" json:"shop_id,omitempty"`
	Record *CustomerRecord `protobuf:"bytes,2,opt,name=record" json:"record,omitempty"`
}

func (m *CreateCustomerRequest) Reset()                    { *m = CreateCustomerRequest{} }
func (m *CreateCustomerRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateCustomerRequest) ProtoMessage()               {}
func (*CreateCustomerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateCustomerRequest) GetShopId() string {
	if m != nil {
		return m.ShopId
	}
	return ""
}

func (m *CreateCustomerRequest) GetRecord() *CustomerRecord {
	if m != nil {
		return m.Record
	}
	return nil
}

type CustomerResponse struct {
	Record *CustomerRecord `protobuf:"bytes,1,opt,name=record" json:"record,omitempty"`
}

func (m *CustomerResponse) Reset()                    { *m = CustomerResponse{} }
func (m *CustomerResponse) String() string            { return proto.CompactTextString(m) }
func (*CustomerResponse) ProtoMessage()               {}
func (*CustomerResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CustomerResponse) GetRecord() *CustomerRecord {
	if m != nil {
		return m.Record
	}
	return nil
}

type ReadCustomersRequest struct {
	ShopId string `protobuf:"bytes,1,opt,name=shop_id,json=shopId" json:"shop_id,omitempty"`
	Offset int32  `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
	Limit  int32  `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
}

func (m *ReadCustomersRequest) Reset()                    { *m = ReadCustomersRequest{} }
func (m *ReadCustomersRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadCustomersRequest) ProtoMessage()               {}
func (*ReadCustomersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ReadCustomersRequest) GetShopId() string {
	if m != nil {
		return m.ShopId
	}
	return ""
}

func (m *ReadCustomersRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ReadCustomersRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type ReadCustomersResponse struct {
	Offset  int32             `protobuf:"varint,1,opt,name=offset" json:"offset,omitempty"`
	Limit   int32             `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
	Total   int32             `protobuf:"varint,3,opt,name=total" json:"total,omitempty"`
	Records []*CustomerRecord `protobuf:"bytes,4,rep,name=records" json:"records,omitempty"`
}

func (m *ReadCustomersResponse) Reset()                    { *m = ReadCustomersResponse{} }
func (m *ReadCustomersResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadCustomersResponse) ProtoMessage()               {}
func (*ReadCustomersResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadCustomersResponse) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ReadCustomersResponse) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ReadCustomersResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ReadCustomersResponse) GetRecords() []*CustomerRecord {
	if m != nil {
		return m.Records
	}
	return nil
}

type ReadCustomerRequest struct {
	ShopId   string `protobuf:"bytes,1,opt,name=shop_id,json=shopId" json:"shop_id,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
}

func (m *ReadCustomerRequest) Reset()                    { *m = ReadCustomerRequest{} }
func (m *ReadCustomerRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadCustomerRequest) ProtoMessage()               {}
func (*ReadCustomerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ReadCustomerRequest) GetShopId() string {
	if m != nil {
		return m.ShopId
	}
	return ""
}

func (m *ReadCustomerRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type UpdateCustomerRequest struct {
	ShopId string          `protobuf:"bytes,1,opt,name=shop_id,json=shopId" json:"shop_id,omitempty"`
	Record *CustomerRecord `protobuf:"bytes,2,opt,name=record" json:"record,omitempty"`
}

func (m *UpdateCustomerRequest) Reset()                    { *m = UpdateCustomerRequest{} }
func (m *UpdateCustomerRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateCustomerRequest) ProtoMessage()               {}
func (*UpdateCustomerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UpdateCustomerRequest) GetShopId() string {
	if m != nil {
		return m.ShopId
	}
	return ""
}

func (m *UpdateCustomerRequest) GetRecord() *CustomerRecord {
	if m != nil {
		return m.Record
	}
	return nil
}

type DeleteCustomerRequest struct {
	ShopId   string `protobuf:"bytes,1,opt,name=shop_id,json=shopId" json:"shop_id,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
}

func (m *DeleteCustomerRequest) Reset()                    { *m = DeleteCustomerRequest{} }
func (m *DeleteCustomerRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteCustomerRequest) ProtoMessage()               {}
func (*DeleteCustomerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DeleteCustomerRequest) GetShopId() string {
	if m != nil {
		return m.ShopId
	}
	return ""
}

func (m *DeleteCustomerRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type DeleteCustomerResponse struct {
}

func (m *DeleteCustomerResponse) Reset()                    { *m = DeleteCustomerResponse{} }
func (m *DeleteCustomerResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteCustomerResponse) ProtoMessage()               {}
func (*DeleteCustomerResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type CustomerRecord struct {
	Username  string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	FirstName string `protobuf:"bytes,2,opt,name=firstName" json:"firstName,omitempty"`
	LastName  string `protobuf:"bytes,3,opt,name=lastName" json:"lastName,omitempty"`
	Phone     string `protobuf:"bytes,4,opt,name=phone" json:"phone,omitempty"`
	Email     string `protobuf:"bytes,5,opt,name=email" json:"email,omitempty"`
	Portrait  string `protobuf:"bytes,6,opt,name=portrait" json:"portrait,omitempty"`
	Role      string `protobuf:"bytes,7,opt,name=role" json:"role,omitempty"`
}

func (m *CustomerRecord) Reset()                    { *m = CustomerRecord{} }
func (m *CustomerRecord) String() string            { return proto.CompactTextString(m) }
func (*CustomerRecord) ProtoMessage()               {}
func (*CustomerRecord) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *CustomerRecord) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CustomerRecord) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *CustomerRecord) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *CustomerRecord) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *CustomerRecord) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CustomerRecord) GetPortrait() string {
	if m != nil {
		return m.Portrait
	}
	return ""
}

func (m *CustomerRecord) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateCustomerRequest)(nil), "com.btdxcx.micro.srv.member.CreateCustomerRequest")
	proto.RegisterType((*CustomerResponse)(nil), "com.btdxcx.micro.srv.member.CustomerResponse")
	proto.RegisterType((*ReadCustomersRequest)(nil), "com.btdxcx.micro.srv.member.ReadCustomersRequest")
	proto.RegisterType((*ReadCustomersResponse)(nil), "com.btdxcx.micro.srv.member.ReadCustomersResponse")
	proto.RegisterType((*ReadCustomerRequest)(nil), "com.btdxcx.micro.srv.member.ReadCustomerRequest")
	proto.RegisterType((*UpdateCustomerRequest)(nil), "com.btdxcx.micro.srv.member.UpdateCustomerRequest")
	proto.RegisterType((*DeleteCustomerRequest)(nil), "com.btdxcx.micro.srv.member.DeleteCustomerRequest")
	proto.RegisterType((*DeleteCustomerResponse)(nil), "com.btdxcx.micro.srv.member.DeleteCustomerResponse")
	proto.RegisterType((*CustomerRecord)(nil), "com.btdxcx.micro.srv.member.CustomerRecord")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Customer service

type CustomerClient interface {
	CreateCustomer(ctx context.Context, in *CreateCustomerRequest, opts ...client.CallOption) (*CustomerResponse, error)
	ReadCustomers(ctx context.Context, in *ReadCustomersRequest, opts ...client.CallOption) (*ReadCustomersResponse, error)
	ReadCustomer(ctx context.Context, in *ReadCustomerRequest, opts ...client.CallOption) (*CustomerResponse, error)
	UpdateCustomer(ctx context.Context, in *UpdateCustomerRequest, opts ...client.CallOption) (*CustomerResponse, error)
	DeleteCustomer(ctx context.Context, in *DeleteCustomerRequest, opts ...client.CallOption) (*DeleteCustomerResponse, error)
}

type customerClient struct {
	c           client.Client
	serviceName string
}

func NewCustomerClient(serviceName string, c client.Client) CustomerClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "com.btdxcx.micro.srv.member"
	}
	return &customerClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *customerClient) CreateCustomer(ctx context.Context, in *CreateCustomerRequest, opts ...client.CallOption) (*CustomerResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Customer.CreateCustomer", in)
	out := new(CustomerResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) ReadCustomers(ctx context.Context, in *ReadCustomersRequest, opts ...client.CallOption) (*ReadCustomersResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Customer.ReadCustomers", in)
	out := new(ReadCustomersResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) ReadCustomer(ctx context.Context, in *ReadCustomerRequest, opts ...client.CallOption) (*CustomerResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Customer.ReadCustomer", in)
	out := new(CustomerResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) UpdateCustomer(ctx context.Context, in *UpdateCustomerRequest, opts ...client.CallOption) (*CustomerResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Customer.UpdateCustomer", in)
	out := new(CustomerResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) DeleteCustomer(ctx context.Context, in *DeleteCustomerRequest, opts ...client.CallOption) (*DeleteCustomerResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Customer.DeleteCustomer", in)
	out := new(DeleteCustomerResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Customer service

type CustomerHandler interface {
	CreateCustomer(context.Context, *CreateCustomerRequest, *CustomerResponse) error
	ReadCustomers(context.Context, *ReadCustomersRequest, *ReadCustomersResponse) error
	ReadCustomer(context.Context, *ReadCustomerRequest, *CustomerResponse) error
	UpdateCustomer(context.Context, *UpdateCustomerRequest, *CustomerResponse) error
	DeleteCustomer(context.Context, *DeleteCustomerRequest, *DeleteCustomerResponse) error
}

func RegisterCustomerHandler(s server.Server, hdlr CustomerHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Customer{hdlr}, opts...))
}

type Customer struct {
	CustomerHandler
}

func (h *Customer) CreateCustomer(ctx context.Context, in *CreateCustomerRequest, out *CustomerResponse) error {
	return h.CustomerHandler.CreateCustomer(ctx, in, out)
}

func (h *Customer) ReadCustomers(ctx context.Context, in *ReadCustomersRequest, out *ReadCustomersResponse) error {
	return h.CustomerHandler.ReadCustomers(ctx, in, out)
}

func (h *Customer) ReadCustomer(ctx context.Context, in *ReadCustomerRequest, out *CustomerResponse) error {
	return h.CustomerHandler.ReadCustomer(ctx, in, out)
}

func (h *Customer) UpdateCustomer(ctx context.Context, in *UpdateCustomerRequest, out *CustomerResponse) error {
	return h.CustomerHandler.UpdateCustomer(ctx, in, out)
}

func (h *Customer) DeleteCustomer(ctx context.Context, in *DeleteCustomerRequest, out *DeleteCustomerResponse) error {
	return h.CustomerHandler.DeleteCustomer(ctx, in, out)
}

func init() {
	proto.RegisterFile("btdxcx.com/micro/member-srv/proto/member/member.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 481 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x95, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x86, 0xf1, 0xb6, 0x4d, 0xb7, 0x03, 0x54, 0xc8, 0x6c, 0x17, 0xab, 0x70, 0xa8, 0x72, 0x5a,
	0x09, 0x6d, 0x0a, 0x5d, 0xf1, 0x04, 0x85, 0x03, 0x08, 0x71, 0x88, 0x84, 0x38, 0x21, 0x94, 0x26,
	0x53, 0x6d, 0xa4, 0xb8, 0x0e, 0xb6, 0xb3, 0x2a, 0xaf, 0xc3, 0xa3, 0xf0, 0x1c, 0x3c, 0x0c, 0xb2,
	0x9d, 0x6c, 0x9a, 0x55, 0xd4, 0x6c, 0xf6, 0xc0, 0xa9, 0xfd, 0x67, 0xfa, 0x7f, 0xe3, 0xf1, 0x78,
	0x54, 0x78, 0xb7, 0xd1, 0xc9, 0x3e, 0xde, 0x07, 0xb1, 0xe0, 0x4b, 0x9e, 0xc6, 0x52, 0x2c, 0x39,
	0xf2, 0x0d, 0xca, 0x4b, 0x25, 0x6f, 0x96, 0xb9, 0x14, 0xba, 0x0a, 0x94, 0x1f, 0x81, 0x8d, 0xd1,
	0x97, 0xb1, 0xe0, 0x41, 0x69, 0xb5, 0xb6, 0x40, 0xc9, 0x9b, 0xc0, 0xfd, 0xc4, 0x2f, 0x60, 0xb6,
	0x96, 0x18, 0x69, 0x5c, 0x17, 0x4a, 0x0b, 0x8e, 0x32, 0xc4, 0x9f, 0x05, 0x2a, 0x4d, 0x5f, 0xc0,
	0x58, 0x5d, 0x8b, 0xfc, 0x47, 0x9a, 0x30, 0xb2, 0x20, 0x17, 0x93, 0xd0, 0x33, 0xf2, 0x63, 0x42,
	0xd7, 0xe0, 0x49, 0x8c, 0x85, 0x4c, 0xd8, 0xc9, 0x82, 0x5c, 0x3c, 0x5e, 0xbd, 0x0e, 0x8e, 0xf0,
	0x83, 0x1a, 0x6b, 0x2c, 0x61, 0x69, 0xf5, 0xbf, 0xc1, 0xb3, 0x3a, 0xa3, 0x72, 0xb1, 0x53, 0x78,
	0x00, 0x26, 0x0f, 0x07, 0x7f, 0x87, 0xb3, 0x10, 0xa3, 0xa4, 0xca, 0xaa, 0xce, 0x76, 0xce, 0xc1,
	0x13, 0xdb, 0xad, 0x42, 0x6d, 0xdb, 0x19, 0x85, 0xa5, 0xa2, 0x67, 0x30, 0xca, 0x52, 0x9e, 0x6a,
	0x36, 0xb0, 0x61, 0x27, 0xfc, 0xdf, 0x04, 0x66, 0x77, 0xf8, 0xe5, 0xe9, 0x6b, 0x0e, 0x69, 0xe7,
	0x9c, 0x1c, 0x70, 0x4c, 0x54, 0x0b, 0x1d, 0x65, 0x15, 0xdd, 0x0a, 0xfa, 0x01, 0xc6, 0xae, 0x0d,
	0xc5, 0x86, 0x8b, 0x41, 0xdf, 0x2b, 0xa8, 0xbc, 0xfe, 0x27, 0x78, 0x7e, 0x78, 0xc6, 0xce, 0x2b,
	0x98, 0xc3, 0x69, 0xa1, 0x50, 0xee, 0x22, 0x8e, 0xf6, 0x94, 0x93, 0xf0, 0x56, 0x9b, 0xf7, 0xf1,
	0x35, 0x4f, 0xfe, 0xfb, 0xfb, 0xf8, 0x0c, 0xb3, 0xf7, 0x98, 0x61, 0x8f, 0xb2, 0xc7, 0x9a, 0x60,
	0x70, 0x7e, 0x97, 0xe6, 0xa6, 0xe6, 0xff, 0x21, 0x30, 0x6d, 0x1e, 0xa1, 0x01, 0x22, 0x4d, 0x10,
	0x7d, 0x05, 0x93, 0x6d, 0x2a, 0x95, 0xfe, 0x52, 0x57, 0xa9, 0x03, 0xc6, 0x99, 0x45, 0x65, 0x72,
	0xe0, 0x9c, 0x95, 0x36, 0x03, 0xcf, 0xaf, 0xc5, 0x0e, 0xd9, 0xd0, 0x26, 0x9c, 0x30, 0x51, 0xe4,
	0x51, 0x9a, 0xb1, 0x91, 0x8b, 0x5a, 0x61, 0x38, 0xb9, 0x90, 0x5a, 0x46, 0xa9, 0x66, 0x9e, 0xe3,
	0x54, 0x9a, 0x52, 0x18, 0x4a, 0x91, 0x21, 0x1b, 0xdb, 0xb8, 0xfd, 0xbe, 0xfa, 0x3b, 0x84, 0xd3,
	0xaa, 0x09, 0x5a, 0xc0, 0xb4, 0xb9, 0xd0, 0x74, 0x75, 0x7c, 0x00, 0x6d, 0xdb, 0x3f, 0xbf, 0xbc,
	0xe7, 0xd0, 0xca, 0x6b, 0x7c, 0x44, 0xf7, 0xf0, 0xb4, 0xb1, 0x17, 0xf4, 0xed, 0x51, 0x42, 0xdb,
	0x8e, 0xce, 0x57, 0x7d, 0x2c, 0xb7, 0x95, 0x05, 0x3c, 0x39, 0x4c, 0xd1, 0x37, 0xf7, 0xa6, 0x3c,
	0xac, 0x59, 0xaa, 0x60, 0xda, 0x5c, 0x89, 0x8e, 0x1b, 0x6e, 0xdd, 0x9f, 0xbe, 0x45, 0x7f, 0xc1,
	0xb4, 0xf9, 0x84, 0x3b, 0x8a, 0xb6, 0x6e, 0xcf, 0xfc, 0xaa, 0x97, 0xc7, 0x95, 0xde, 0x78, 0xf6,
	0x6f, 0xe4, 0xea, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xaf, 0x71, 0xf0, 0xf4, 0x7f, 0x06, 0x00,
	0x00,
}
