// Code generated by protoc-gen-go. DO NOT EDIT.
// source: btdxcx.com/micro/member-srv/proto/member/member.proto

/*
Package com_btdxcx_micro_srv_member is a generated protocol buffer package.

It is generated from these files:
	btdxcx.com/micro/member-srv/proto/member/member.proto

It has these top-level messages:
	CreateCustomerRequest
	CustomerResponse
	ReadCustomersRequest
	ReadCustomersResponse
	ReadCustomerRequest
	ReadCustomerFormNameRequest
	UpdateCustomerRequest
	DeleteCustomerRequest
	DeleteCustomerResponse
	CustomerRecord
*/
package com_btdxcx_micro_srv_member

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateCustomerRequest struct {
	ShopId string          `protobuf:"bytes,1,opt,name=shop_id,json=shopId" json:"shop_id,omitempty"`
	Record *CustomerRecord `protobuf:"bytes,2,opt,name=record" json:"record,omitempty"`
}

func (m *CreateCustomerRequest) Reset()                    { *m = CreateCustomerRequest{} }
func (m *CreateCustomerRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateCustomerRequest) ProtoMessage()               {}
func (*CreateCustomerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateCustomerRequest) GetShopId() string {
	if m != nil {
		return m.ShopId
	}
	return ""
}

func (m *CreateCustomerRequest) GetRecord() *CustomerRecord {
	if m != nil {
		return m.Record
	}
	return nil
}

type CustomerResponse struct {
	Record *CustomerRecord `protobuf:"bytes,1,opt,name=record" json:"record,omitempty"`
}

func (m *CustomerResponse) Reset()                    { *m = CustomerResponse{} }
func (m *CustomerResponse) String() string            { return proto.CompactTextString(m) }
func (*CustomerResponse) ProtoMessage()               {}
func (*CustomerResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CustomerResponse) GetRecord() *CustomerRecord {
	if m != nil {
		return m.Record
	}
	return nil
}

type ReadCustomersRequest struct {
	ShopId string `protobuf:"bytes,1,opt,name=shop_id,json=shopId" json:"shop_id,omitempty"`
	Offset int32  `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
	Limit  int32  `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
}

func (m *ReadCustomersRequest) Reset()                    { *m = ReadCustomersRequest{} }
func (m *ReadCustomersRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadCustomersRequest) ProtoMessage()               {}
func (*ReadCustomersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ReadCustomersRequest) GetShopId() string {
	if m != nil {
		return m.ShopId
	}
	return ""
}

func (m *ReadCustomersRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ReadCustomersRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type ReadCustomersResponse struct {
	Offset  int32             `protobuf:"varint,1,opt,name=offset" json:"offset,omitempty"`
	Limit   int32             `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
	Total   int32             `protobuf:"varint,3,opt,name=total" json:"total,omitempty"`
	Records []*CustomerRecord `protobuf:"bytes,4,rep,name=records" json:"records,omitempty"`
}

func (m *ReadCustomersResponse) Reset()                    { *m = ReadCustomersResponse{} }
func (m *ReadCustomersResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadCustomersResponse) ProtoMessage()               {}
func (*ReadCustomersResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadCustomersResponse) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ReadCustomersResponse) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ReadCustomersResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ReadCustomersResponse) GetRecords() []*CustomerRecord {
	if m != nil {
		return m.Records
	}
	return nil
}

type ReadCustomerRequest struct {
	ShopId string `protobuf:"bytes,1,opt,name=shop_id,json=shopId" json:"shop_id,omitempty"`
	Id     string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
}

func (m *ReadCustomerRequest) Reset()                    { *m = ReadCustomerRequest{} }
func (m *ReadCustomerRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadCustomerRequest) ProtoMessage()               {}
func (*ReadCustomerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ReadCustomerRequest) GetShopId() string {
	if m != nil {
		return m.ShopId
	}
	return ""
}

func (m *ReadCustomerRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadCustomerFormNameRequest struct {
	ShopId string `protobuf:"bytes,1,opt,name=shop_id,json=shopId" json:"shop_id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *ReadCustomerFormNameRequest) Reset()                    { *m = ReadCustomerFormNameRequest{} }
func (m *ReadCustomerFormNameRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadCustomerFormNameRequest) ProtoMessage()               {}
func (*ReadCustomerFormNameRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ReadCustomerFormNameRequest) GetShopId() string {
	if m != nil {
		return m.ShopId
	}
	return ""
}

func (m *ReadCustomerFormNameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UpdateCustomerRequest struct {
	ShopId string          `protobuf:"bytes,1,opt,name=shop_id,json=shopId" json:"shop_id,omitempty"`
	Id     string          `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Record *CustomerRecord `protobuf:"bytes,3,opt,name=record" json:"record,omitempty"`
}

func (m *UpdateCustomerRequest) Reset()                    { *m = UpdateCustomerRequest{} }
func (m *UpdateCustomerRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateCustomerRequest) ProtoMessage()               {}
func (*UpdateCustomerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *UpdateCustomerRequest) GetShopId() string {
	if m != nil {
		return m.ShopId
	}
	return ""
}

func (m *UpdateCustomerRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateCustomerRequest) GetRecord() *CustomerRecord {
	if m != nil {
		return m.Record
	}
	return nil
}

type DeleteCustomerRequest struct {
	ShopId string `protobuf:"bytes,1,opt,name=shop_id,json=shopId" json:"shop_id,omitempty"`
	Id     string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteCustomerRequest) Reset()                    { *m = DeleteCustomerRequest{} }
func (m *DeleteCustomerRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteCustomerRequest) ProtoMessage()               {}
func (*DeleteCustomerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *DeleteCustomerRequest) GetShopId() string {
	if m != nil {
		return m.ShopId
	}
	return ""
}

func (m *DeleteCustomerRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteCustomerResponse struct {
}

func (m *DeleteCustomerResponse) Reset()                    { *m = DeleteCustomerResponse{} }
func (m *DeleteCustomerResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteCustomerResponse) ProtoMessage()               {}
func (*DeleteCustomerResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type CustomerRecord struct {
	Id                  string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Username            string   `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	FirstName           string   `protobuf:"bytes,3,opt,name=firstName" json:"firstName,omitempty"`
	LastName            string   `protobuf:"bytes,4,opt,name=lastName" json:"lastName,omitempty"`
	Phone               string   `protobuf:"bytes,5,opt,name=phone" json:"phone,omitempty"`
	Email               string   `protobuf:"bytes,6,opt,name=email" json:"email,omitempty"`
	Portrait            string   `protobuf:"bytes,7,opt,name=portrait" json:"portrait,omitempty"`
	Gender              string   `protobuf:"bytes,8,opt,name=gender" json:"gender,omitempty"`
	Birthday            int64    `protobuf:"varint,9,opt,name=birthday" json:"birthday,omitempty"`
	Groups              []string `protobuf:"bytes,10,rep,name=groups" json:"groups,omitempty"`
	RegisteredAt        int64    `protobuf:"varint,11,opt,name=registered_at,json=registeredAt" json:"registered_at,omitempty"`
	AccessAt            int64    `protobuf:"varint,12,opt,name=access_at,json=accessAt" json:"access_at,omitempty"`
	Integral            int64    `protobuf:"varint,13,opt,name=integral" json:"integral,omitempty"`
	BuyNumber           int64    `protobuf:"varint,14,opt,name=buy_number,json=buyNumber" json:"buy_number,omitempty"`
	TotalPurchaseAmount int64    `protobuf:"varint,15,opt,name=totalPurchaseAmount" json:"totalPurchaseAmount,omitempty"`
	Role                string   `protobuf:"bytes,16,opt,name=role" json:"role,omitempty"`
	Superior            string   `protobuf:"bytes,17,opt,name=superior" json:"superior,omitempty"`
}

func (m *CustomerRecord) Reset()                    { *m = CustomerRecord{} }
func (m *CustomerRecord) String() string            { return proto.CompactTextString(m) }
func (*CustomerRecord) ProtoMessage()               {}
func (*CustomerRecord) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *CustomerRecord) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CustomerRecord) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CustomerRecord) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *CustomerRecord) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *CustomerRecord) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *CustomerRecord) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CustomerRecord) GetPortrait() string {
	if m != nil {
		return m.Portrait
	}
	return ""
}

func (m *CustomerRecord) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *CustomerRecord) GetBirthday() int64 {
	if m != nil {
		return m.Birthday
	}
	return 0
}

func (m *CustomerRecord) GetGroups() []string {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *CustomerRecord) GetRegisteredAt() int64 {
	if m != nil {
		return m.RegisteredAt
	}
	return 0
}

func (m *CustomerRecord) GetAccessAt() int64 {
	if m != nil {
		return m.AccessAt
	}
	return 0
}

func (m *CustomerRecord) GetIntegral() int64 {
	if m != nil {
		return m.Integral
	}
	return 0
}

func (m *CustomerRecord) GetBuyNumber() int64 {
	if m != nil {
		return m.BuyNumber
	}
	return 0
}

func (m *CustomerRecord) GetTotalPurchaseAmount() int64 {
	if m != nil {
		return m.TotalPurchaseAmount
	}
	return 0
}

func (m *CustomerRecord) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *CustomerRecord) GetSuperior() string {
	if m != nil {
		return m.Superior
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateCustomerRequest)(nil), "com.btdxcx.micro.srv.member.CreateCustomerRequest")
	proto.RegisterType((*CustomerResponse)(nil), "com.btdxcx.micro.srv.member.CustomerResponse")
	proto.RegisterType((*ReadCustomersRequest)(nil), "com.btdxcx.micro.srv.member.ReadCustomersRequest")
	proto.RegisterType((*ReadCustomersResponse)(nil), "com.btdxcx.micro.srv.member.ReadCustomersResponse")
	proto.RegisterType((*ReadCustomerRequest)(nil), "com.btdxcx.micro.srv.member.ReadCustomerRequest")
	proto.RegisterType((*ReadCustomerFormNameRequest)(nil), "com.btdxcx.micro.srv.member.ReadCustomerFormNameRequest")
	proto.RegisterType((*UpdateCustomerRequest)(nil), "com.btdxcx.micro.srv.member.UpdateCustomerRequest")
	proto.RegisterType((*DeleteCustomerRequest)(nil), "com.btdxcx.micro.srv.member.DeleteCustomerRequest")
	proto.RegisterType((*DeleteCustomerResponse)(nil), "com.btdxcx.micro.srv.member.DeleteCustomerResponse")
	proto.RegisterType((*CustomerRecord)(nil), "com.btdxcx.micro.srv.member.CustomerRecord")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Customer service

type CustomerClient interface {
	CreateCustomer(ctx context.Context, in *CreateCustomerRequest, opts ...client.CallOption) (*CustomerResponse, error)
	ReadCustomers(ctx context.Context, in *ReadCustomersRequest, opts ...client.CallOption) (*ReadCustomersResponse, error)
	ReadCustomer(ctx context.Context, in *ReadCustomerRequest, opts ...client.CallOption) (*CustomerResponse, error)
	ReadCustomerFormName(ctx context.Context, in *ReadCustomerFormNameRequest, opts ...client.CallOption) (*CustomerResponse, error)
	UpdateCustomer(ctx context.Context, in *UpdateCustomerRequest, opts ...client.CallOption) (*CustomerResponse, error)
	DeleteCustomer(ctx context.Context, in *DeleteCustomerRequest, opts ...client.CallOption) (*DeleteCustomerResponse, error)
}

type customerClient struct {
	c           client.Client
	serviceName string
}

func NewCustomerClient(serviceName string, c client.Client) CustomerClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "com.btdxcx.micro.srv.member"
	}
	return &customerClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *customerClient) CreateCustomer(ctx context.Context, in *CreateCustomerRequest, opts ...client.CallOption) (*CustomerResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Customer.CreateCustomer", in)
	out := new(CustomerResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) ReadCustomers(ctx context.Context, in *ReadCustomersRequest, opts ...client.CallOption) (*ReadCustomersResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Customer.ReadCustomers", in)
	out := new(ReadCustomersResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) ReadCustomer(ctx context.Context, in *ReadCustomerRequest, opts ...client.CallOption) (*CustomerResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Customer.ReadCustomer", in)
	out := new(CustomerResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) ReadCustomerFormName(ctx context.Context, in *ReadCustomerFormNameRequest, opts ...client.CallOption) (*CustomerResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Customer.ReadCustomerFormName", in)
	out := new(CustomerResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) UpdateCustomer(ctx context.Context, in *UpdateCustomerRequest, opts ...client.CallOption) (*CustomerResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Customer.UpdateCustomer", in)
	out := new(CustomerResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) DeleteCustomer(ctx context.Context, in *DeleteCustomerRequest, opts ...client.CallOption) (*DeleteCustomerResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Customer.DeleteCustomer", in)
	out := new(DeleteCustomerResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Customer service

type CustomerHandler interface {
	CreateCustomer(context.Context, *CreateCustomerRequest, *CustomerResponse) error
	ReadCustomers(context.Context, *ReadCustomersRequest, *ReadCustomersResponse) error
	ReadCustomer(context.Context, *ReadCustomerRequest, *CustomerResponse) error
	ReadCustomerFormName(context.Context, *ReadCustomerFormNameRequest, *CustomerResponse) error
	UpdateCustomer(context.Context, *UpdateCustomerRequest, *CustomerResponse) error
	DeleteCustomer(context.Context, *DeleteCustomerRequest, *DeleteCustomerResponse) error
}

func RegisterCustomerHandler(s server.Server, hdlr CustomerHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Customer{hdlr}, opts...))
}

type Customer struct {
	CustomerHandler
}

func (h *Customer) CreateCustomer(ctx context.Context, in *CreateCustomerRequest, out *CustomerResponse) error {
	return h.CustomerHandler.CreateCustomer(ctx, in, out)
}

func (h *Customer) ReadCustomers(ctx context.Context, in *ReadCustomersRequest, out *ReadCustomersResponse) error {
	return h.CustomerHandler.ReadCustomers(ctx, in, out)
}

func (h *Customer) ReadCustomer(ctx context.Context, in *ReadCustomerRequest, out *CustomerResponse) error {
	return h.CustomerHandler.ReadCustomer(ctx, in, out)
}

func (h *Customer) ReadCustomerFormName(ctx context.Context, in *ReadCustomerFormNameRequest, out *CustomerResponse) error {
	return h.CustomerHandler.ReadCustomerFormName(ctx, in, out)
}

func (h *Customer) UpdateCustomer(ctx context.Context, in *UpdateCustomerRequest, out *CustomerResponse) error {
	return h.CustomerHandler.UpdateCustomer(ctx, in, out)
}

func (h *Customer) DeleteCustomer(ctx context.Context, in *DeleteCustomerRequest, out *DeleteCustomerResponse) error {
	return h.CustomerHandler.DeleteCustomer(ctx, in, out)
}

func init() {
	proto.RegisterFile("btdxcx.com/micro/member-srv/proto/member/member.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 679 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xc1, 0x4e, 0xdb, 0x4c,
	0x10, 0xfe, 0x9d, 0x90, 0x80, 0x07, 0xc8, 0x4f, 0x17, 0x42, 0x57, 0xa1, 0x95, 0x22, 0xf7, 0x82,
	0x54, 0x61, 0x68, 0x50, 0xa5, 0x9e, 0xaa, 0x22, 0xda, 0x4a, 0xed, 0x01, 0x55, 0x96, 0xaa, 0x9e,
	0x2a, 0xe4, 0xd8, 0x03, 0x59, 0xc9, 0xf6, 0xba, 0xbb, 0x6b, 0x44, 0x4e, 0x3d, 0xf5, 0x45, 0xfa,
	0x5e, 0x7d, 0x80, 0xbe, 0x45, 0xb5, 0xbb, 0x76, 0xe2, 0x44, 0x11, 0x21, 0x39, 0xe1, 0x6f, 0x66,
	0xbf, 0x6f, 0x76, 0x66, 0x87, 0x4f, 0x81, 0xd7, 0x43, 0x15, 0xdf, 0x47, 0xf7, 0x7e, 0xc4, 0xd3,
	0xd3, 0x94, 0x45, 0x82, 0x9f, 0xa6, 0x98, 0x0e, 0x51, 0x9c, 0x48, 0x71, 0x77, 0x9a, 0x0b, 0xae,
	0xaa, 0x40, 0xf9, 0xc7, 0x37, 0x31, 0x72, 0x14, 0xf1, 0xd4, 0x2f, 0xa9, 0x86, 0xe6, 0x4b, 0x71,
	0xe7, 0xdb, 0x23, 0x5e, 0x01, 0xdd, 0x4b, 0x81, 0xa1, 0xc2, 0xcb, 0x42, 0x2a, 0x9e, 0xa2, 0x08,
	0xf0, 0x47, 0x81, 0x52, 0x91, 0xa7, 0xb0, 0x29, 0x47, 0x3c, 0xbf, 0x66, 0x31, 0x75, 0xfa, 0xce,
	0xb1, 0x1b, 0xb4, 0x35, 0xfc, 0x14, 0x93, 0x4b, 0x68, 0x0b, 0x8c, 0xb8, 0x88, 0x69, 0xa3, 0xef,
	0x1c, 0x6f, 0x0f, 0x5e, 0xfa, 0x0f, 0xe8, 0xfb, 0x53, 0x59, 0x4d, 0x09, 0x4a, 0xaa, 0xf7, 0x0d,
	0xf6, 0xa6, 0x19, 0x99, 0xf3, 0x4c, 0x62, 0x4d, 0xd8, 0x59, 0x5f, 0xf8, 0x3b, 0x1c, 0x04, 0x18,
	0xc6, 0x55, 0x56, 0x2e, 0x6d, 0xe7, 0x10, 0xda, 0xfc, 0xe6, 0x46, 0xa2, 0x32, 0xed, 0xb4, 0x82,
	0x12, 0x91, 0x03, 0x68, 0x25, 0x2c, 0x65, 0x8a, 0x36, 0x4d, 0xd8, 0x02, 0xef, 0xb7, 0x03, 0xdd,
	0x39, 0xfd, 0xf2, 0xf6, 0x53, 0x1d, 0x67, 0xb1, 0x4e, 0xa3, 0xa6, 0xa3, 0xa3, 0x8a, 0xab, 0x30,
	0xa9, 0xd4, 0x0d, 0x20, 0x1f, 0x60, 0xd3, 0xb6, 0x21, 0xe9, 0x46, 0xbf, 0xb9, 0xea, 0x08, 0x2a,
	0xae, 0xf7, 0x16, 0xf6, 0xeb, 0x77, 0x5c, 0x3a, 0x82, 0x0e, 0x34, 0x98, 0x7d, 0x4d, 0x37, 0x68,
	0xb0, 0xd8, 0xfb, 0x0c, 0x47, 0x75, 0xfe, 0x47, 0x2e, 0xd2, 0xab, 0x30, 0xc5, 0xa5, 0x3a, 0x04,
	0x36, 0xb2, 0x30, 0xc5, 0x52, 0xc9, 0x7c, 0x7b, 0xbf, 0x1c, 0xe8, 0x7e, 0xcd, 0xe3, 0x55, 0x16,
	0x6c, 0xee, 0x3a, 0xb5, 0xbd, 0x68, 0xae, 0xbf, 0x17, 0xef, 0xa0, 0xfb, 0x1e, 0x13, 0x5c, 0xff,
	0x1a, 0x1e, 0x85, 0xc3, 0x79, 0x05, 0xfb, 0xf4, 0xde, 0xdf, 0x26, 0x74, 0x66, 0xcb, 0x96, 0x64,
	0x67, 0xd2, 0x43, 0x0f, 0xb6, 0x0a, 0x89, 0xa2, 0x36, 0x9e, 0x09, 0x26, 0xcf, 0xc0, 0xbd, 0x61,
	0x42, 0x2a, 0x3d, 0x63, 0xd3, 0xa2, 0x1b, 0x4c, 0x03, 0x9a, 0x99, 0x84, 0x65, 0x72, 0xc3, 0x32,
	0x2b, 0xac, 0xb7, 0x28, 0x1f, 0xf1, 0x0c, 0x69, 0xcb, 0x24, 0x2c, 0xd0, 0x51, 0x4c, 0x43, 0x96,
	0xd0, 0xb6, 0x8d, 0x1a, 0xa0, 0x75, 0x72, 0x2e, 0x94, 0x08, 0x99, 0xa2, 0x9b, 0x56, 0xa7, 0xc2,
	0x7a, 0x77, 0x6f, 0x31, 0x8b, 0x51, 0xd0, 0x2d, 0x3b, 0x02, 0x8b, 0x34, 0x67, 0xc8, 0x84, 0x1a,
	0xc5, 0xe1, 0x98, 0xba, 0x7d, 0xe7, 0xb8, 0x19, 0x4c, 0xb0, 0xe1, 0x08, 0x5e, 0xe4, 0x92, 0x42,
	0xbf, 0x69, 0x38, 0x06, 0x91, 0x17, 0xb0, 0x2b, 0xf0, 0x96, 0x49, 0x85, 0x02, 0xe3, 0xeb, 0x50,
	0xd1, 0x6d, 0x43, 0xdc, 0x99, 0x06, 0x2f, 0x14, 0x39, 0x02, 0x37, 0x8c, 0x22, 0x94, 0x52, 0x1f,
	0xd8, 0xb1, 0xca, 0x36, 0x70, 0xa1, 0x74, 0x55, 0x96, 0x29, 0xbc, 0x15, 0x61, 0x42, 0x77, 0x6d,
	0xae, 0xc2, 0xe4, 0x39, 0xc0, 0xb0, 0x18, 0x5f, 0x67, 0x85, 0x7e, 0x6b, 0xda, 0x31, 0x59, 0x77,
	0x58, 0x8c, 0xaf, 0x4c, 0x80, 0x9c, 0xc1, 0xbe, 0xf9, 0x4f, 0xfa, 0x52, 0x88, 0x68, 0x14, 0x4a,
	0xbc, 0x48, 0x79, 0x91, 0x29, 0xfa, 0xbf, 0x39, 0xb7, 0x28, 0xa5, 0x77, 0x56, 0xf0, 0x04, 0xe9,
	0x9e, 0xdd, 0x59, 0xfd, 0xad, 0x2f, 0x20, 0x8b, 0x1c, 0x05, 0xe3, 0x82, 0x3e, 0xb1, 0xa3, 0xaa,
	0xf0, 0xe0, 0x4f, 0x0b, 0xb6, 0xaa, 0xb7, 0x26, 0x05, 0x74, 0x66, 0xcd, 0x93, 0x0c, 0x1e, 0xde,
	0xcd, 0x45, 0x4e, 0xdb, 0x3b, 0x79, 0xe4, 0x3e, 0x97, 0xdb, 0xf6, 0x1f, 0xb9, 0x87, 0xdd, 0x19,
	0x0f, 0x22, 0xaf, 0x1e, 0x54, 0x58, 0xe4, 0x87, 0xbd, 0xc1, 0x2a, 0x94, 0x49, 0x65, 0x0e, 0x3b,
	0xf5, 0x14, 0x39, 0x7b, 0xb4, 0xca, 0x7a, 0xcd, 0x92, 0x9f, 0xb3, 0x76, 0x5e, 0x59, 0x11, 0x79,
	0xf3, 0xe8, 0xc2, 0x73, 0xee, 0xb5, 0xea, 0x05, 0x24, 0x74, 0x66, 0xed, 0x6b, 0xc9, 0x13, 0x2f,
	0xf4, 0xba, 0x55, 0x8b, 0x8e, 0xa1, 0x33, 0x6b, 0x35, 0x4b, 0x8a, 0x2e, 0x74, 0xb6, 0xde, 0xf9,
	0x4a, 0x1c, 0x5b, 0x7a, 0xd8, 0x36, 0xbf, 0x19, 0xce, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0xd2,
	0xac, 0xf9, 0xb8, 0x6c, 0x08, 0x00, 0x00,
}
