// Code generated by protoc-gen-go. DO NOT EDIT.
// source: btdxcx.com/micro/shop-srv/proto/shop/shop_key.proto

/*
Package com_btdxcx_micro_srv_shop is a generated protocol buffer package.

It is generated from these files:
	btdxcx.com/micro/shop-srv/proto/shop/shop_key.proto

It has these top-level messages:
	ShopKeyID
	KeyRequest
	KeyResponse
	DeleteKeyResponse
	IntrospectRequest
	IntrospectResponse
*/
package com_btdxcx_micro_srv_shop

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ShopKeyID struct {
	BackKey string `protobuf:"bytes,1,opt,name=back_key,json=backKey" json:"back_key,omitempty"`
	MiniKey string `protobuf:"bytes,2,opt,name=mini_key,json=miniKey" json:"mini_key,omitempty"`
}

func (m *ShopKeyID) Reset()                    { *m = ShopKeyID{} }
func (m *ShopKeyID) String() string            { return proto.CompactTextString(m) }
func (*ShopKeyID) ProtoMessage()               {}
func (*ShopKeyID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ShopKeyID) GetBackKey() string {
	if m != nil {
		return m.BackKey
	}
	return ""
}

func (m *ShopKeyID) GetMiniKey() string {
	if m != nil {
		return m.MiniKey
	}
	return ""
}

type KeyRequest struct {
	Uuid string `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
}

func (m *KeyRequest) Reset()                    { *m = KeyRequest{} }
func (m *KeyRequest) String() string            { return proto.CompactTextString(m) }
func (*KeyRequest) ProtoMessage()               {}
func (*KeyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *KeyRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type KeyResponse struct {
	Key *ShopKeyID `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
}

func (m *KeyResponse) Reset()                    { *m = KeyResponse{} }
func (m *KeyResponse) String() string            { return proto.CompactTextString(m) }
func (*KeyResponse) ProtoMessage()               {}
func (*KeyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *KeyResponse) GetKey() *ShopKeyID {
	if m != nil {
		return m.Key
	}
	return nil
}

type DeleteKeyResponse struct {
}

func (m *DeleteKeyResponse) Reset()                    { *m = DeleteKeyResponse{} }
func (m *DeleteKeyResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteKeyResponse) ProtoMessage()               {}
func (*DeleteKeyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type IntrospectRequest struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
}

func (m *IntrospectRequest) Reset()                    { *m = IntrospectRequest{} }
func (m *IntrospectRequest) String() string            { return proto.CompactTextString(m) }
func (*IntrospectRequest) ProtoMessage()               {}
func (*IntrospectRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *IntrospectRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type IntrospectResponse struct {
	Type   string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Uuid   string `protobuf:"bytes,2,opt,name=uuid" json:"uuid,omitempty"`
	Active bool   `protobuf:"varint,3,opt,name=active" json:"active,omitempty"`
}

func (m *IntrospectResponse) Reset()                    { *m = IntrospectResponse{} }
func (m *IntrospectResponse) String() string            { return proto.CompactTextString(m) }
func (*IntrospectResponse) ProtoMessage()               {}
func (*IntrospectResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *IntrospectResponse) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *IntrospectResponse) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *IntrospectResponse) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func init() {
	proto.RegisterType((*ShopKeyID)(nil), "com.btdxcx.micro.srv.shop.ShopKeyID")
	proto.RegisterType((*KeyRequest)(nil), "com.btdxcx.micro.srv.shop.KeyRequest")
	proto.RegisterType((*KeyResponse)(nil), "com.btdxcx.micro.srv.shop.KeyResponse")
	proto.RegisterType((*DeleteKeyResponse)(nil), "com.btdxcx.micro.srv.shop.DeleteKeyResponse")
	proto.RegisterType((*IntrospectRequest)(nil), "com.btdxcx.micro.srv.shop.IntrospectRequest")
	proto.RegisterType((*IntrospectResponse)(nil), "com.btdxcx.micro.srv.shop.IntrospectResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for ShopKey service

type ShopKeyClient interface {
	Create(ctx context.Context, in *KeyRequest, opts ...client.CallOption) (*KeyResponse, error)
	Read(ctx context.Context, in *KeyRequest, opts ...client.CallOption) (*KeyResponse, error)
	Delete(ctx context.Context, in *KeyRequest, opts ...client.CallOption) (*DeleteKeyResponse, error)
	Introspect(ctx context.Context, in *IntrospectRequest, opts ...client.CallOption) (*IntrospectResponse, error)
}

type shopKeyClient struct {
	c           client.Client
	serviceName string
}

func NewShopKeyClient(serviceName string, c client.Client) ShopKeyClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "com.btdxcx.micro.srv.shop"
	}
	return &shopKeyClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *shopKeyClient) Create(ctx context.Context, in *KeyRequest, opts ...client.CallOption) (*KeyResponse, error) {
	req := c.c.NewRequest(c.serviceName, "ShopKey.Create", in)
	out := new(KeyResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopKeyClient) Read(ctx context.Context, in *KeyRequest, opts ...client.CallOption) (*KeyResponse, error) {
	req := c.c.NewRequest(c.serviceName, "ShopKey.Read", in)
	out := new(KeyResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopKeyClient) Delete(ctx context.Context, in *KeyRequest, opts ...client.CallOption) (*DeleteKeyResponse, error) {
	req := c.c.NewRequest(c.serviceName, "ShopKey.Delete", in)
	out := new(DeleteKeyResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopKeyClient) Introspect(ctx context.Context, in *IntrospectRequest, opts ...client.CallOption) (*IntrospectResponse, error) {
	req := c.c.NewRequest(c.serviceName, "ShopKey.Introspect", in)
	out := new(IntrospectResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ShopKey service

type ShopKeyHandler interface {
	Create(context.Context, *KeyRequest, *KeyResponse) error
	Read(context.Context, *KeyRequest, *KeyResponse) error
	Delete(context.Context, *KeyRequest, *DeleteKeyResponse) error
	Introspect(context.Context, *IntrospectRequest, *IntrospectResponse) error
}

func RegisterShopKeyHandler(s server.Server, hdlr ShopKeyHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&ShopKey{hdlr}, opts...))
}

type ShopKey struct {
	ShopKeyHandler
}

func (h *ShopKey) Create(ctx context.Context, in *KeyRequest, out *KeyResponse) error {
	return h.ShopKeyHandler.Create(ctx, in, out)
}

func (h *ShopKey) Read(ctx context.Context, in *KeyRequest, out *KeyResponse) error {
	return h.ShopKeyHandler.Read(ctx, in, out)
}

func (h *ShopKey) Delete(ctx context.Context, in *KeyRequest, out *DeleteKeyResponse) error {
	return h.ShopKeyHandler.Delete(ctx, in, out)
}

func (h *ShopKey) Introspect(ctx context.Context, in *IntrospectRequest, out *IntrospectResponse) error {
	return h.ShopKeyHandler.Introspect(ctx, in, out)
}

func init() {
	proto.RegisterFile("btdxcx.com/micro/shop-srv/proto/shop/shop_key.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 336 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0x4f, 0x6b, 0xfa, 0x40,
	0x10, 0xf5, 0x1f, 0x51, 0xc7, 0xcb, 0xcf, 0xf9, 0x41, 0x51, 0x4f, 0x12, 0x6a, 0xf1, 0x50, 0x57,
	0x50, 0xe8, 0xbd, 0xd4, 0x1e, 0x24, 0xb7, 0xb4, 0x50, 0x7a, 0x92, 0xb8, 0x0e, 0x18, 0x6c, 0xdc,
	0x34, 0xbb, 0x8a, 0xf9, 0x08, 0xfd, 0xd6, 0x65, 0x37, 0xab, 0x11, 0xa4, 0xa9, 0x87, 0x5e, 0xc2,
	0xbe, 0xcc, 0x7b, 0x33, 0xef, 0xcd, 0x2e, 0x4c, 0x97, 0x6a, 0x75, 0xe0, 0x07, 0xc6, 0x45, 0x34,
	0x8e, 0x42, 0x9e, 0x88, 0xb1, 0x5c, 0x8b, 0x78, 0x24, 0x93, 0xfd, 0x38, 0x4e, 0x84, 0xca, 0xa0,
	0xf9, 0x2c, 0x36, 0x94, 0x32, 0xf3, 0x0f, 0xbb, 0x5c, 0x44, 0xcc, 0x0a, 0x8d, 0x88, 0xc9, 0x64,
	0xcf, 0x34, 0xc9, 0x7d, 0x84, 0xe6, 0xcb, 0x5a, 0xc4, 0x1e, 0xa5, 0xf3, 0x19, 0x76, 0xa1, 0xb1,
	0x0c, 0xf8, 0x46, 0x2b, 0x3b, 0xe5, 0x7e, 0x79, 0xd8, 0xf4, 0xeb, 0x1a, 0x7b, 0x94, 0xea, 0x52,
	0x14, 0x6e, 0x43, 0x53, 0xaa, 0x64, 0x25, 0x8d, 0x3d, 0x4a, 0xdd, 0x3e, 0x80, 0x47, 0xa9, 0x4f,
	0x9f, 0x3b, 0x92, 0x0a, 0x11, 0x6a, 0xbb, 0x5d, 0xb8, 0xb2, 0x7a, 0x73, 0x76, 0x9f, 0xa1, 0x65,
	0x18, 0x32, 0x16, 0x5b, 0x49, 0xf8, 0x00, 0xd5, 0xe3, 0x84, 0xd6, 0xe4, 0x96, 0xfd, 0x68, 0x8e,
	0x9d, 0x9c, 0xf9, 0x5a, 0xe0, 0xfe, 0x87, 0xf6, 0x8c, 0x3e, 0x48, 0xd1, 0x59, 0x33, 0x77, 0x00,
	0xed, 0xf9, 0x56, 0x25, 0x42, 0xc6, 0xc4, 0xd5, 0xd1, 0xc4, 0xbf, 0x7c, 0x42, 0x33, 0xd3, 0xbe,
	0x02, 0x9e, 0xd3, 0xac, 0x13, 0x84, 0x9a, 0x4a, 0x63, 0x3a, 0x9a, 0xd5, 0xe7, 0x53, 0x80, 0x4a,
	0x1e, 0x00, 0x6f, 0xc0, 0x09, 0xb8, 0x0a, 0xf7, 0xd4, 0xa9, 0xf6, 0xcb, 0xc3, 0x86, 0x6f, 0xd1,
	0xe4, 0xab, 0x0a, 0x75, 0x6b, 0x12, 0xdf, 0xc1, 0x79, 0x4a, 0x28, 0x50, 0x84, 0x83, 0x82, 0x48,
	0xf9, 0xa6, 0x7a, 0x77, 0xbf, 0xd1, 0x6c, 0xc2, 0x12, 0xbe, 0x41, 0xcd, 0xa7, 0x60, 0xf5, 0xf7,
	0x8d, 0x17, 0xe0, 0x64, 0x1b, 0xbd, 0xb6, 0xf5, 0x7d, 0x01, 0xed, 0xf2, 0x6e, 0x4a, 0x18, 0x02,
	0xe4, 0x6b, 0xc7, 0x22, 0xf5, 0xc5, 0x25, 0xf6, 0x46, 0x57, 0xb2, 0xb3, 0x61, 0x4b, 0xc7, 0xbc,
	0xf5, 0xe9, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x28, 0x65, 0xe0, 0xe3, 0x22, 0x03, 0x00, 0x00,
}
